### ISSUE TITLE
Outdated package on conda-forge?

### ISSUE THREAD

**Issue by pioboch** [heremaps/xyz-spaces-python#103]
Hi guys, 
I wanted to let you know that I recently installed xyzspace package from conda-forge (version '0.4.0') and it looks that some functionalities are missing there. 
E.g. according to the documentation one of the parameters of space.spatial_search() is 'force_2d' (to skip Z coordinate in the response). When I wanted to use it I got:
TypeError: spatial_search() got an unexpected keyword argument 'force_2d'

Thanks,
Piotr

**Comment by deeplook** [comment]
Thanks for the comment! I guess it is time for a new release... ;)

**Comment by sackh** [comment]
@pioboch - The readthedocs shows default documentation taken from the code in the master branch. To see the released latest version documentation used a stable version. 

Latest documentation from the code in the master branch: https://xyz-spaces-python.readthedocs.io/en/latest/
Latest Released version documentation: https://xyz-spaces-python.readthedocs.io/en/stable/ 
We will soon make a new release.

**Comment by pioboch** [comment]
Indeed, I was using the 'latest' documentation. Thanks!
