### ISSUE TITLE
Resolution param for hexbin clusters has no effect

### ISSUE THREAD

**Issue by deeplook** [heremaps/xyz-spaces-python#75]
Sample snippet:

```python
from ipyleaflet import GeoJSON, Map
from turfpy.measurement import center
from xyzspaces import XYZ
from xyzspaces.datasets import get_countries_data

xyz_pro_token = "******"
xyz = XYZ(credentials=xyz_pro_token)
space = xyz.spaces.new(title="Hexbin Cluster Demo", description="Hexbin Cluster Demo")
afg = get_countries_data()["features"][0]
space.add_features(features=geojson.FeatureCollection([afg]))
try:
    fc = None
    # Allowed params: [resolution, relativeResolution, absoluteResolution,
    #                  property, pointmode, countmode, noBuffer]
    fc = space.cluster("hexbin", clustering_params={"absoluteResolution": 5})
finally:
    space.delete()

c = list(reversed(center(afg)["geometry"]["coordinates"]))
m = Map(center=c, zoom=5)
if fc:
    m += GeoJSON(data=fc)
m
```

**Comment by sackh** [comment]
There are some changes in hub APIs in recent versions this might help - https://github.com/heremaps/xyz-hub/releases?after=1.10.1

**Comment by sackh** [comment]
I could see different responses from API  for different values of `absoluteResolution`.

**absoluteResolution: 0**
<img width="1182" alt="resolution0" src="https://user-images.githubusercontent.com/8600927/92879069-55973c80-f42a-11ea-9dfd-0aa5ebce180a.png">


**absoluteResolution: 1**
<img width="1199" alt="resolution1" src="https://user-images.githubusercontent.com/8600927/92879116-6182fe80-f42a-11ea-9544-c2f5434ba757.png">

**absoluteResolution: 5**
<img width="1189" alt="resolution5" src="https://user-images.githubusercontent.com/8600927/92879196-7364a180-f42a-11ea-9cc2-6d461e49b72f.png">
