### ISSUE TITLE
Explore GitHub actions for CI

### ISSUE THREAD

**Issue by sackh** [heremaps/xyz-spaces-python#82]
GitHub actions provide Linux, macOS, and Windows build for CI.
for more information see: https://github.com/sdras/awesome-actions

**Comment by deeplook** [comment]
There are also other interesting options based on [GitHub actions](https://docs.github.com/en/free-pro-team@latest/actions) like this one adding a [MyBinder.org](https://mybinder.org) badge to PRs: https://mybinder.readthedocs.io/en/latest/howto/gh-actions-badges.html

**Comment by deeplook** [comment]
This is mandatory now by the end of Q1 2021.

**Comment by sackh** [comment]
Fixed in #111
